apiVersion: "v1.0.0"
kind: "DataProduct"
id: "shelf-warmers"
name: "Shelf Warmers"
status: "draft"
description:
  purpose: "A list of articles with no sales in last 6 months"
team:
  name: "fulfillment"
outputPorts:
  - name: "snowflake_fulfillment_shelf_warmers"
    version: "1"
    type: "snowflake"
    contractId: "snowflake_fulfillment_shelf_warmers"
    customProperties:
      - property: "database"
        value: "DP_SHELF_WARMERS"
      - property: "schema"
        value: "OP_SHELF_WARMERS_V1"
      - property: "table"
        value: "SHELF_WARMERS"
      - property: "contractServer"
        value: "production"
      - property: "displayName"
        value: "SHELF_WARMERS"
      - property: "status"
        value: "draft"
      - property: "environment"
        value: "prod"
customProperties:
  - property: "icon"
    value: "snowflake"
  - property: "type"
    value: "consumer-aligned"
  - property: "visibility"
    value: "internal"
  - property: "dataProductBuilder"
    value: "https://github.com/entropy-data/dataproduct-builder-demo"
  - property: "repository"
    value: "https://github.com/entropy-data/dp_demo_shelf_warmers"
